matrix:
  include:
    - stage: testing
      language: python
      python:
        - "3.6"

      env:
          - MPI=mpich
          - MPI=openmpi
      before_install:
          - test $MPI == mpich && PACKAGES='mpich libmpich-dev' || true
          - test $MPI == openmpi && PACKAGES='openmpi-bin libopenmpi-dev' || true
          - sudo apt-get update -qq && sudo apt-get install -qq $PACKAGES
                  
      install:
        - ls .
        - pwd
        - rm -f ~/.ssh/id_rsa
        - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
        - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
        - chmod og-wx ~/.ssh/authorized_keys
        - ssh-keyscan -H localhost >> ~/.ssh/known_hosts        
        - pip install -r requirements.txt
        - git clone https://github.com/djgroen/FabSim3.git 
        - cd FabSim3
        - pwd
        - pip install -r requirements.txt
        - sed "s/your-username/`whoami`/g" <<< cat deploy/machines_user_example.yml > deploy/machines_user.yml
        - fab localhost install_plugin:FabFlee
        - ls FabSim3
        - cd ..
        - ls .
      script:
        - export PATH=~/FabSim3/bin:$PATH
        - export PYTHONPATH=~/FabSim3:$PYTHONPATH        
        - cd .
        - python -m pytest --log-cli-level=10 tests/


